dataset: 'azure'
sync_method: strict
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: False
  const_speed_assumption: True
  gt_camera: False
  lr: 0.003
  pixels: 1000
  iters: 50
mapping:
  every_frame: 5
  vis_freq: 50
  vis_inside_freq: 30
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 10
  pixels: 3000
  iters_first: 1000
  iters: 70
cam:
  H: 480 
  W: 640
  fx: 607.595
  fy: 606.62
  cx: 324.293
  cy: 240.799
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 0
mapping:
  bound: [[-11.0,8.0],[-1.5,3.5],[-9.5,7.5]]
  marching_cubes_bound: [[-11.0,8.0],[-1.5,3.5],[-9.5,7.5]]
data:
  input_folder: /home/lair99/uncertainty_nerf/nice-slam_mine/Datasets/stair/frames
  output: output/stair/frames